### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by cgatian** [mafintosh/hypervision#2]
Saw this trending on Libraries.io, curious to know how to get started.

**Comment by mafintosh** [comment]
run the install instructions :)

open the app. click record.
open the app again, paste the link

you can share the link with friends you want watching your desktop also! :)

**Comment by cgatian** [comment]
Does this work on Windows? Npm is giving me errors about Python. I'll paste when I'm back on my machine.

**Comment by sveisvei** [comment]
Cool demo at the end by @mafintosh here: https://opbeat.com/community/posts/fresh-off-the-p2p-factory-by-mathias-buus/ 👍

**Comment by louiscenter** [comment]
@cgatian if you're interested, I also wrote an introduction to `hypervision` which you can find here: https://louis.center/p2p-hypervision.html

You mentioned an error on Windows as well. I don't have access to a Windows machine myself to test, but if the issue is still persisting, I'd recommend opening another issue thread so I can try and diagnose the problem for you :)
